/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("prox.kotlin-common-conventions")

}
dependencies {
    implementation("com.github.ajalt.clikt:clikt:3.1.0")
}