/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("prox.kotlin-console-conventions")
}

application {
    mainClass.set("com.test.prox.console.ConsoleKt")
}

dependencies {
    api(project(":app"))
}
